language:
  - ruby

rvm:
  - 2.3.1

env:
  global:
    - TZ='Asia/Tokyo'

install:
  - bundle install --path vendor/bundle

script:
  - bundle update
  - ./scripts/create_pullrequest.sh

cache:
  directories:
    - vendor/bundle
