language:
  - ruby

rvm:
  - 2.3.1

env:
  global:
    - TZ='Asia/Tokyo'
  secure: "a4Mob+LoXwfVLpzgdFWlxLL56zn3jyBU7dmCU17aV823V/ig1uFmErN0LVyofc9F/A/DEjfzWhgTgjrg+jHLPKgNyFPlYG2f9dNsyI5Dl73xVCz31uIynbp9gymCVHq/vbWa3eLE+jtCZjcS/vQWokA3lu3okAOarNJpwskHx066+/GSoKtCQodAe1Zcw0OE3Fohdu8FwPEYyxjFHMpKTFhatJSDZ0/6EHfSBnjuKuv+UTXNxZIdbt3EduUOLuKgn3RcI5HPzJVfoC2o1jPju4FXK2fTU6uXjs8szQVqvyRD41TD4Kf5pdRF9R1IL5JD+ySi4ZAuoGNEdrHlvyry4DqW4rQtdRBbMRk5j/Dv0hzMDXrClaKJKge9yKt4170d7MI4QTqwK5XRr09nWlGSXhRf2gUbHnvf5bjPa0OK9Hiv3LEsZesm+aGwwcU/zrjCGVs+r5FznoSBnqR1Ojn7ySv/5DJvHpvMdjV4sldAi6vBBJA3TLs4WIKGwf+LU9J587BmAsrzsgUL6DtzmJQkUm/NdSFVfwVCsl+hfUfpGM1SDgaC6RDGuBjnlLxLF2qQ8VZAJ3oL6q1214UdnME6HzVaoF+NWs+2dqW4syUQ2sLbA+ZYhPzKXUvV24BNf9nbDvi+zOeH7DN+1MnwLi7+uW/JLVldLnOP5aEUh8dHfRQ="

install:
  - bundle install --path vendor/bundle

script:
  - bundle update
  - ./scripts/create_pullrequest.sh

cache:
  directories:
    - vendor/bundle
